from typing import Protocol

class DatabaseProtocol(Protocol):
    def ping(self) -> bool: ...
    def add_upload(self, filename: str, blob_url: str) -> None: ...
    def set_status(self, filename: str, status: str, page_count: int = 0) -> None: ...
    def remove_upload(self, filename: str) -> None: ...
    def list_uploads(self) -> list[dict]: ...
    def save_chunks(
        self,
        filename: str,
        pages: list[int],
        indexes: list[int],
        texts: list[str],
        vectors: list[list[float]],
    ) -> None: ...
    def delete_chunks(self, filename: str) -> None: ...
    def search_chunks(
        self,
        query_vector: list[float],
        query_text: str = "",
        k: int = 5,
        filenames: list[str] | None = None,
        search_mode: str = "hybrid",
    ) -> list[dict]: ...
    def add_message(self, role: str, content: str, chunks: list[dict] | None = None) -> None: ...
    def get_messages(self, limit: int = 50) -> list[dict]: ...


class EmbedderProtocol(Protocol):
    async def embed(self, texts: list[str], batch_size: int | None = None) -> list[list[float]]: ...


class GeneratorProtocol(Protocol):
    async def generate(self, question: str, chunks: list[dict], history: list[dict]) -> str: ...


class ExtractorProtocol(Protocol):
    def extract_chunks(self, file_path: str) -> tuple[list[int], list[int], list[str], int]: ...
